### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by RutsuKun** [xdk78/shinden-api#2]
Search anime don't work
![screenshot_2018-05-07-22-53-07-887_com aor droidedit pro](https://user-images.githubusercontent.com/14915249/39724658-a8a9d12e-5249-11e8-8df0-1aff6250fa4e.png)
![screenshot_2018-05-07-22-50-42-696_com sonelli juicessh](https://user-images.githubusercontent.com/14915249/39724659-a8d7ef3c-5249-11e8-81a0-a212b52a7e7f.png)

**Comment by xdk78** [comment]
Oh, you right, I will look at this later.
